name: CI

on:
  push:
    branches: [ main, master, prod, develop ]
  pull_request:
    branches: [ main, master, prod, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11, 17, 21]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run tests
      run: mvn clean test

    - name: Generate test report
      run: mvn surefire-report:report

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-java-${{ matrix.java-version }}
        path: target/surefire-reports/
        retention-days: 30

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Compile project
      run: mvn clean compile

    - name: Package project
      run: mvn package -DskipTests=true

    - name: Generate sources
      run: mvn source:jar

    - name: Generate javadoc
      run: mvn javadoc:jar

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: target/*.jar
        retention-days: 7

  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run Maven verify
      run: mvn clean verify -DskipTests=true

    - name: Check for security vulnerabilities
      run: mvn org.owasp:dependency-check-maven:check || true

  validate-jitpack:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Validate JitPack compatibility
      run: |
        echo "Validating JitPack configuration..."
        if [ -f "jitpack.yml" ]; then
          echo "✅ jitpack.yml found"
          cat jitpack.yml
        else
          echo "❌ jitpack.yml not found"
          exit 1
        fi

    - name: Test JitPack build simulation
      run: |
        echo "Simulating JitPack build process..."
        mvn clean install -DskipTests=true -B -V

        if [ -f "target/reductio-*.jar" ]; then
          echo "✅ JAR artifacts generated successfully"
          ls -la target/*.jar
        else
          echo "❌ No JAR artifacts found"
          exit 1
        fi
